.TH FWUPDATE "1" "May 2015" "fwupdate" "User Commands"
.SH NAME
fwupdate \- update system firmware
.SH SYNOPSIS
.B fwupdate
[\fI\,OPTION\/\fR...]
.SH DESCRIPTION
.TP
\fB\-a\fR, \fB\-\-apply=\fR<guid> <firmware.cap>
Apply firmware updates
.TP
\fB\-l\fR, \fB\-\-list\fR
List supported firmware updates
.TP
\fB\-s\fR, \fB\-\-supported\fR
Query for firmware update support
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Work quietly
.SS "Help options:"
.TP
\-?, \fB\-\-help\fR
Show this help message
.TP
\fB\-\-usage\fR
Display brief usage message
