.TH FWUPDATE "1" "May 2015" "fwupdate" "User Commands"
.SH NAME
fwupdate \- update system firmware
.SH SYNOPSIS
.B fwupdate
[\fI\,OPTION\/\fR...]
.SH DESCRIPTION
.TP
\fB\-a\fR, \fB\-\-apply=\fR<guid> <firmware.cap>
Apply firmware updates\&. <guid> and <firmware.cap> have to be separates arguments; don't do \fB\-\-apply=\fR"<guid> <firmware.cap>" but \fB\-\-apply=\fR<guid> <firmware.cap>
.TP
\fB\-l\fR, \fB\-\-list\fR
List supported firmware updates
.TP
\fB\-s\fR, \fB\-\-supported\fR
Query for firmware update support
.TP
\fB\-i\fR, \fB\-\-info\fR
Show the information of firmware update status
.TP
\fB\-e\fR, \fB\-\-enable\fR
Enable firmware update support on supported systems (will require a reboot)
.TP
\fB\-d\fR | \fB\-D\fR, \fB\-\-set\-debug\fR | \fB\-\-unset\-debug\fR
Set or unset the persistent debugging verbosity flag used when running updates.  This state is persistent until changed.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Work quietly
.TP
\fB\-q\fR, \fB\-\-force\fR
Forces flash even if GUID isn't in ESRT (EFI System Resource Table)
.TP
\fB\-p\fR, \fB\-\-esp-path=\fR<esp-path>
Directory where the ESP (EFI System Partition) is currently mounted\&. By default the fwupdate assume the ESP is mounted in /boot/efi/.
.TP
\fB\-F\fR, \fB\-\-dont-use-existing-media-path\fR
By default when you apply a firmware update, \fBfwupdate\fR check the current EFI firmware <guid> and recorded file path (use \fB--info\fR to get those informations)\&. If the current EFI firmware <guid> is the same as the update, \fBfwupdate\fR will try to use the same recorded file path\&. This can be a problem if, for example, you want to change the \fBESP subdirectory\fR[1] used by \fBfwupdate\fR\&.
.sp
This option makes \fBfwupdate\fR behave as if there wasn't any recorded file path.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be more verbose on errors
.SS "Help options:"
.TP
\fB\-?\fR, \fB\-\-help\fR
Show this help message
.TP
\fB\-\-usage\fR
Display brief usage message
.SH "NOTES"
.IP " 1." 4
ESP subdirectory
.RS 4
\%http://www.uefi.org/registry
.RE
